version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - run:
          name: Check version
          command: cargo --version
      - run:
          name: Check formatting
          command: cargo fmt --all -- --check
      - run:
          name: Run Tests
          command: cargo test --al
