version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check version
          command: cargo --version
      - run:
          name: Check formatting
          command: cargo fmt --all -- --check
      - run:
          name: Run Tests
          command: cargo test --al
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
